name: Auto Notify Every 6min

on:
  # 6分ごとに自動起動するタイマー設定
  schedule:
    - cron: '*/6 * * * *'
  
  # 手動でも動かせるようにボタンも残しておく
  workflow_dispatch:

jobs:
  auto-notify:
    runs-on: ubuntu-latest
    steps:
      - name: 通知を送信
        run: |
          WEBHOOK_URL="https://discord.com/api/webhooks/1551500158578204795/REWJQc8zR2BWc6JnG7bi97fS3Wkp0d2Nzuz_LKLcBnCEQidrobRdyyuMC4EovaV2vDdw" # ← あなたのDiscord URL
          
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content": "⏰ [自動タイマー起動] 6分ごとの定期パトロールです！"}' \
               $WEBHOOK_URL
